import {
  tenis,
  verde,
  cinto,
  smartwatch,
  jaqueta,
  vestido3,
  jaquetaf,
  blusa,
  novidade1,
  novidade2,
  novidade3,
  novidade4,
  novidade5,
  pd1,
  pd2,
  pd3,
  pd4,
  pd5,
  pd6,
  pd7,
  pd8,
  pd9,
  pd10,
  pd11,
  pd12,
  pd13,
  pd14,
  pd15,
  pd16,
  pd17,
  pd18,
  pd19,
  pd20,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Início",
    link: "/",
  },
  {
    _id: 1002,
    title: "Produtos",
    link: "/produtos",
  },
  {
    _id: 1003,
    title: "Sobre",
    link: "/sobre",
  },
  {
    _id: 1004,
    title: "Contato",
    link: "/contato",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: tenis,
    productName: "Tênis Street",
    price: "115.00",
    color: "Preto",
    badge: true,
    des: "Tênis Street Em Material Sintético Com Cadarço E Recortes Preto.",
  },
  {
    _id: "202",
    img: verde,
    productName: "Calça Fluida Verde",
    price: "110.00",
    color: "Verde",
    badge: true,
    des: "Calça Fluida Em Viscolinho Com Amarração No Cós Verde.",
  },
  {
    _id: "203",
    img: cinto,
    productName: "Kit 02 Cintos",
    price: "50.00",
    color: "Marrom/Bege",
    badge: true,
    des: "Kit 02 Cintos Estreitos Com Diferentes Modelos De Fivela Marrom/Bege.",
  },
  {
    _id: "204",
    img: smartwatch,
    productName: "Smartwatch",
    price: "220.00",
    color: "Preto",
    badge: true,
    des: "Relógio Mormaii Smartwatch Molife Com Pulseira Em Silicone MOLIFEAB/8P Preto.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: novidade5,
    productName: "Vestido New Midi",
    price: "68.00",
    color: "Laranja",
    badge: true,
    des: "Vestido New Midi De Alça Em Linho Com Estampa Araras E Abacaxis Laranja.",
  },
  {
    _id: 1002,
    img: verde,
    productName: "Calça Fluida Verde",
    price: "110.00",
    color: "Verde",
    badge: true,
    des: "Calça Fluida Em Viscolinho Com Amarração No Cós Verde.",
  },
  {
    _id: 1003,
    img: cinto,
    productName: "Kit 02 Cintos",
    price: "50.00",
    color: "Marrom/Bege",
    badge: true,
    des: "Kit 02 Cintos Estreitos Com Diferentes Modelos De Fivela Marrom/Bege.",
  },
  {
    _id: 1004,
    img: smartwatch,
    productName: "Smartwatch",
    price: "220.00",
    color: "Preto",
    badge: true,
    des: "Relógio Mormaii Smartwatch Molife Com Pulseira Em Silicone MOLIFEAB/8P Preto.",
  },
  {
    _id: 1005,
    img: jaqueta,
    productName: "Jaqueta Gola Alta",
    price: "135.00",
    color: "Verde",
    badge: true,
    des: "Jaqueta Alongada Em Poliamida Com Gola Alta E Zíper Verde.",
  },
  {
    _id: 1006,
    img: vestido3,
    productName: "Vestido Midi Plus Size",
    price: "90.00",
    color: "Verde",
    badge: false,
    des: "Vestido Midi em Tule Transpassado com Estampa Étnica Curve & Plus Size.",
  },
  {
    _id: 1007,
    img: jaquetaf,
    productName: "Jaqueta Esportiva",
    price: "69.00",
    color: "Roxo",
    badge: true,
    des: "Jaqueta Esportiva Em Modal Com Capuz E Fechamento Com Zíper Roxo.",
  },
  {
    _id: 1008,
    img: blusa,
    productName: "Blusa Em Renda Azul",
    price: "92.00",
    color: "Azul",
    badge: false,
    des: "Blusa Em Renda Com Amarração E Estampa De Florezinhas Azul",
  },
  {
    _id: 1009,
    img: novidade1,
    productName: "Macaquinho Sarja Branco",
    price: "52.00",
    color: "Branco",
    badge: true,
    des: "Macaquinho Sarja Com Alcinha E Amarração Traseira Branco.",
  },
  {
    _id: 1010,
    img: novidade2,
    productName: "Camiseta Oversized Em Algodão",
    price: "45.00",
    color: "Cinza escuro",
    badge: true,
    des: "Camiseta Oversized Em Algodão Com Bordado Stronger Na Gola Cinza Escuro.",
  },
  {
    _id: 1011,
    img: novidade3,
    productName: "Camiseta Relaxed Em Algodão",
    price: "77.00",
    color: "Branco",
    badge: false,
    des: "Camiseta Relaxed Em Algodão Com Gola Canelada Branco.",
  },
  {
    _id: 1012,
    img: novidade4,
    productName: "Vestido Midi Preto",
    price: "60.00",
    color: "Preto",
    badge: false,
    des: "Vestido New Midi Em Tule Bordado Com Flores E Manga Bufante Preto.",
  },
  {
    _id: 1013,
    img: pd1,
    productName: "Saia New Midi",
    price: "120.00",
    color: "Azul",
    badge: false,
    des: "Saia New Midi Em Tule Com Babados E Estampa Tropical Azul.",
  },

  {
    _id: 1014,
    img: pd2,
    productName: "Camisa Em Linho Laranja",
    price: "59.00",
    color: "Laranja",
    badge: true,
    des: "Camisa Em Linho Com Botões E Bolso Bordado De Miçangas Laranja.",
  },
  {
    _id: 1015,
    img: pd3,
    productName: "Camiseta Com Estampa",
    price: "49.00",
    color: "Preto",
    badge: false,
    des: "Camiseta Regular Em Meia Malha Com Estampa Gato Meowgic Preto.",
  },
  {
    _id: 1016,
    img: pd4,
    productName: "Calça Jogger",
    price: "132.00",
    color: "Preto",
    badge: true,
    des: "Calça Jogger em Poliamida com Bolsos Cargo.",
  },
  {
    _id: 1017,
    img: pd5,
    productName: "Short Runner Plus Size",
    price: "59.90",
    color: "Preto",
    badge: false,
    des: "Short Runner Em Poliamida Com Amarração Curve & Plus Size Preto.",
  },
  {
    _id: 1018,
    img: pd6,
    productName: "Calça Pantalona",
    price: "95.00",
    color: "Bege",
    badge: true,
    des: "Calça Pantalona Acetinada Com Pences Nas Costas Bege.",
  },
  {
    _id: 1019,
    img: pd7,
    productName: "Pijama Macacão.",
    price: "30.00",
    color: "Preto",
    badge: true,
    des: "Pijama Macacão Em Viscolycra Com Transpassado E Estampa Poá Curve & Plus Size Preto.",
  },
  {
    _id: 1021,
    img: pd8,
    productName: "Camiseta Estampa Meownster",
    price: "35.00",
    color: "Azul",
    badge: true,
    des: "Camiseta Em Meia Malha Com Estampa Meownster Azul.",
  },
  {
    _id: 1020,
    img: pd9,
    productName: "Calça Jogger Básica",
    price: "79.00",
    color: "Barrom",
    badge: true,
    des: "Calça Jogger Básica em Sarja com Bolso Cargo e Elástico na Perna.",
  },
  {
    _id: 1022,
    img: pd10,
    productName: "Sandália Rasteira",
    price: "37.00",
    color: "Bege",
    badge: true,
    des: "Sandália Rasteira Com Cabedal H Bege.",
  },
  {
    _id: 1023,
    img: pd11,
    productName: "Bolsa Shoulder",
    price: "70.00",
    color: "Dourado",
    badge: true,
    des: "Bolsa Shoulder Baguete Metalizada.",
  },
  {
    _id: 1024,
    img: pd12,
    productName: "Camiseta Manga Curta Rosa",
    price: "29.00",
    color: "Rosa",
    badge: true,
    des: "Camiseta Manga Curta Em Algodão Estampa Hexágono Minimalista E Mini Coqueiro Rosa.",
  },
  {
    _id: 1025,
    img: pd13,
    productName: "Camiseta Comfort Verde",
    price: "27.00",
    color: "Verde",
    badge: true,
    des: "Camiseta Comfort Em Algodão Com Estampa De Lettering Verde.",
  },
  {
    _id: 1026,
    img: pd14,
    productName: "Relógio Mormaii Digital",
    price: "140.00",
    color: "Preto",
    badge: true,
    des: "Relógio Mormaii Digital com Pulseira e Caixa em Borracha MO3660AC/8R.",
  },
  {
    _id: 1027,
    img: pd15,
    productName: "Bermuda Em Algodão Marrom",
    price: "42.00",
    color: "Marrom",
    badge: true,
    des: "Bermuda Em Algodão Estonado Com Bolsos E Etiqueta Na Barra Marrom.",
  },
  {
    _id: 1028,
    img: pd16,
    productName: "Calça Slim Em Linho",
    price: "89.00",
    color: "Preto",
    badge: true,
    des: "Calça Slim Em Linho Com Cós Elástico E Amarração Preto.",
  },
  {
    _id: 1029,
    img: pd17,
    productName: "Bolsa Baguete Pequena",
    price: "59.00",
    color: "Azul",
    badge: false,
    des: "Bolsa Baguete Pequena Com Detalhe Na Alça E Fechamento Em Zíper Azul.",
  },
  {
    _id: 1030,
    img: pd18,
    productName: "Sandália Meia Pata",
    price: "85.00",
    color: "Azul",
    badge: true,
    des: "Sandália Meia Pata Em Jeans Azul.",
  },
  {
    _id: 1031,
    img: pd19,
    productName: "Cinto Western",
    price: "25.00",
    color: "Preto",
    badge: false,
    des: "Cinto Western Com Duas Fivelas Preto.",
  },
  {
    _id: 1032,
    img: pd20,
    productName: "Camiseta Em Meia Malha Amarelo",
    price: "44.00",
    color: "Amarelo",
    badge: true,
    des: "Camiseta Em Meia Malha Mesclada Com Manga Curta Amarelo.",
  },
];
// =================== PaginationItems End here =================
